### ISSUE TITLE
step "Enable Pull Request Automerge" has been skipping 

### ISSUE THREAD

**Issue by olga-density** [peter-evans/enable-pull-request-automerge#1062]
Hello Peter!

Thank you for integration. I use `Create Pull Request` and it works amazingly.
However, I have a very strange issue with `Enable Pull Request Automerge` such as action skipping this step.
I've added below the debug logs. If you have any ideas/tips, it would be very much appreciated. 

```
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
```
Debug logs:
```
0s
##[debug]Evaluating condition for step: 'Enable Pull Request Automerge'
##[debug]Evaluating: (success() && (steps.cpr.outputs.pull-request-operation == 'created'))
##[debug]Evaluating And:
##[debug]..Evaluating success:
##[debug]..=> true
##[debug]..Evaluating Equal:
##[debug]....Evaluating Index:
##[debug]......Evaluating Index:
##[debug]........Evaluating Index:
##[debug]..........Evaluating steps:
##[debug]..........=> Object
##[debug]..........Evaluating String:
##[debug]..........=> 'cpr'
##[debug]........=> Object
##[debug]........Evaluating String:
##[debug]........=> 'outputs'
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'pull-request-operation'
##[debug]....=> null
##[debug]....Evaluating String:
##[debug]....=> 'created'
##[debug]..=> false
##[debug]=> false
##[debug]Expanded: (true && (null == 'created'))
##[debug]Result: false
```

**Comment by peter-evans** [comment]
Hi @olga-density 

Apologies for the slow response.

It's skipping because the output `pull-request-operation` is evaluating to `null`. It will be null when no action was taken by the create-pull-request action. The possible actions are `created`, `updated` and `closed`. For example, if the action ran and there were no changes to raise in a PR then no PR is created and the result of `pull-request-operation` is `null`. This is the correct behaviour. You only want to set automerge on newly created PRs.

**Comment by olga-density** [comment]
Hey @peter-evans, thank you for getting back to me.
Correct, I see that auto-merge skipped and when I looked at PR it required approval.
I was trying to add the auto-approval
```
      # - name: Auto approve
      #   if: steps.cpr.outputs.pull-request-operation == 'created'
      #   run: gh pr review --approve "${{ steps.cpr.outputs.pull-request-number }}"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
but hot this error
```
Run gh pr review --approve "31"
  gh pr review --approve "31"
  shell: /usr/bin/bash -e {0}
  env:
    PULL_REQUEST_NUMBER: [3](https://github.com/DensityCo/helm-charts/actions/runs/6087166314/job/16515139564#step:8:3)1
    GH_TOKEN: ***
failed to run git: fatal: not a git repository (or any of the parent directories): .git
```
if you have any ideas/advice, I would very much appreciate so.

**Comment by peter-evans** [comment]
The error from the GitHub CLI is telling you that it can't find a git repository locally. Have you checked out the repository?

**Comment by olga-density** [comment]
Hey Peter! 

yes, I did.
Sorry, for late response. I was busy with another project. I'll try to troubleshoot this issue again.
Thank you for your response!
