### ISSUE TITLE
Getting warning in actions about unexpected input 'merge-method'

### ISSUE THREAD

**Issue by IceTDrinker** [peter-evans/enable-pull-request-automerge#238]
![image](https://user-images.githubusercontent.com/49040125/142892254-d215ca56-fc1e-4386-8883-c99457aa6e33.png)

The action works but there is a warning emitted when checking a run

**Comment by peter-evans** [comment]
Hi @IceTDrinker 

This warning normally occurs when the input doesn't exist in `action.yml`, but in this case `merge-method` exists.
https://github.com/peter-evans/enable-pull-request-automerge/blob/main/action.yml#L13-L15

Please could you show your workflow so I can see how you are using the action.

**Comment by IceTDrinker** [comment]
my mistake, it seems some other action was given this parameter as input (and does not expect it), sorry for the inconvenience and thanks for the reply, I only knew of this action with this parameter name.

**Comment by peter-evans** [comment]
No problem. Glad you solved it.
