### ISSUE TITLE
Automerge can't find recently created PR

### ISSUE THREAD

**Issue by JMoserCricut** [peter-evans/enable-pull-request-automerge#286]
I'm using the peter-evans/create-pull-request@v3 and immediately after using this to enable the automerging. Sometimes the PR can't be found, it appears to be a bit of a race condition where the github api hasn't been updated quite yet, so the automerge action can't find the PR
![image](https://user-images.githubusercontent.com/59970772/150401527-3988240a-3770-4dc4-acd2-b03bcc9e7cb2.png)

**Comment by peter-evans** [comment]
Hi @JMoserCricut 

As you mentioned, perhaps GitHub's infrastructure doesn't update fast enough sometimes. I would imagine that to be quite a rare occurrence though. Is this happening a lot?

I guess the simplest workaround is to wait some time in between creating the PR and enabling automerge.
```yml
- run: sleep 5s
```

One other thing to check. Are you using the same `token` to create the PR and enable automerge? If using the same token (and hence the same user) I believe that GitHub's infra caches recently created resources. If you use a different token/user then there might be a delay before the second user can "see" the created resources. That's just my experience using the API, I don't actually know the internals of GitHub.

**Comment by JMoserCricut** [comment]
@peter-evans Thanks for the response, We are seeing it quite frequently, we are using a different token, the create PR is using the temporary token while the automerge requires the PAT. So that does seem to make sense with what you've said. 

I think adding the few second delay as you've suggested is best approach for my usecase thanks!
