### ISSUE TITLE
Feat: Add https proxy env support

### ISSUE THREAD

**Issue by AriehSchneier** [peter-evans/enable-pull-request-automerge#300]
Can you please add proxy support like you did for the [create-pull-request](https://github.com/peter-evans/create-pull-request/issues/733) action?

It may be just a matter of bumping octokit to version 3.12.0 or later, see [here](https://github.com/octokit/action.js/pull/329).

Thanks in advance

**Comment by peter-evans** [comment]
Hi @AriehSchneier 

I added the feature and released as `v1.2.0` / `v1`.

Thanks for reporting!

**Comment by AriehSchneier** [comment]
Very quick turn around! TYVM
