### ISSUE TITLE
Error "Pull request is in clean status"

### ISSUE THREAD

**Issue by williamboman** [peter-evans/enable-pull-request-automerge#343]
Hello! I'm trying to add this to one of my repos and I'm running into [this error](https://github.com/williamboman/nvim-lsp-installer/runs/6878574574?check_suite_focus=true) when trying run the action. The full workflow file [can be found here](https://github.com/williamboman/nvim-lsp-installer/blob/main/.github/workflows/run-autogen.yml). I couldn't really find anything on the internets, do you perhaps have any ideas what might be going wrong? My best guess is that it's attempting to enable automerge before it's ready (definition of ready being: no checks have been registered with the PR yet)

**Comment by adrianioana** [comment]
Hi. @williamboman  I am also getting a similar error :( 
`Error: ["Pull request Pull request is in unstable status"]`

**Comment by peter-evans** [comment]
Hi @williamboman 

I've not seen this error before. Is it happening consistently, or just occasionally?

> My best guess is that it's attempting to enable automerge before it's ready

You could try waiting a few seconds in a workflow step to see if that solves it. Perhaps there is a small delay on GitHub's side before the PR is ready, as you suggest.

**Comment by williamboman** [comment]
What do you think about doing this inside this workflow instead? I feel like it'd be neat if one did not have to worry about these race conditions. I've come up with a somewhat naive approach in https://github.com/peter-evans/enable-pull-request-automerge/pull/344. Wdyt?

**Comment by williamboman** [comment]
So I actually debugged this a bit closer and I don't believe this is happening because of some race condition, there has to be something else going on. I added a retry mechanism that sleeps for 30s before retrying, but it's still consistently failing with the same error, even if the [PR checks are all registered and even completed](https://user-images.githubusercontent.com/6705160/173957844-ae0c7b56-fc2f-4cd3-86d2-a0f731b9dd70.png).

**Comment by williamboman** [comment]
I think I know what it might've been. I had not made any checks explicitly required under the repo settings - I had only enabled the checkbox itself. If you don't manually add specific checks that are required I believe GitHub's native automerge feature simply doesn't apply

<img width="799" alt="Screenshot 2022-06-16 at 01 42 51" src="https://user-images.githubusercontent.com/6705160/173960184-860adec5-b200-425c-87d0-ebe150df0fdd.png">
"

**Comment by williamboman** [comment]
Thos are pretty bad error messages from their API if you ask me 🙈, it had me running in circles. Would you be open for parsing these error messages or even wrapping the entire exception with a custom error message, like:

```
catch (e) {
  core.error(e)
  core.error("Unable to enable automerge. Make sure you have enabled branch protection with at least one status check marked as required. See https://github.com/peter-evans/enable-pull-request-automerge#conditions for more information.")
}
```

**Comment by peter-evans** [comment]
I would be happy to parse and capture the `clean status` error, because I think we can be fairly confident about what that means and how it occurs. I would prefer to capture and handle that one specifically, rather than output a custom error message for all exceptions.

**Comment by williamboman** [comment]
Cool! I went ahead and implemented it in #345! Not sure if you want logging in the helper module, but that's where I'd put it.

**Comment by peter-evans** [comment]
Merged and released. Thanks!

I think we can consider this closed. If other error messages emerge we can handle those separately.

**Comment by Haegi** [comment]
Hi all,
