### ISSUE TITLE
Automerging the PR vs enabling the automerge flag

### ISSUE THREAD

**Issue by ns-ggeorgiev** [peter-evans/enable-pull-request-automerge#393]
Hi,

I am interested in github action that will help me to merge the PR not simply try to enable the automerge flag.

The subtle difference is going to be, that for branches that are not protected it should simply merge the pr instead of reporting error.

Same thing for the case where the PR is already checked, instead of failing to enable the auto merge flag, it should just merge it.

Are you interested in enhancing this tool in that direction?

**Comment by peter-evans** [comment]
Hi @ns-ggeorgiev 

I would like to keep the scope and functionality of this action focused on just enabling GitHub's automerge feature. What might work well is to use this action inside a [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action). You can then write some logic steps to decide whether to run this action, or do something else.
