### ISSUE TITLE
Does this action work with merge queues?

### ISSUE THREAD

**Issue by peter-evans** [peter-evans/enable-pull-request-automerge#785]
https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/

Investigated a little and it appears to be using the same GraphQL API to "merge when ready." There are some notes in the GraphQL documentation that suggest this is the case.

![image](https://user-images.githubusercontent.com/18365890/217694748-58ffddd6-e494-4253-a9d3-c25ab637db4e.png)

Todo:
- Test the action with merge queues
- Update documentation

**Comment by smeeklai** [comment]
I'm using the action and tried it on the merge queue beta feature. Looks like I got below error from the action when it ran. It works fine previously before enabled the feature.

```
Run peter-evans/enable-pull-request-automerge@v2
Fetching pull request ID
Enabling auto-merge on pull request ID PR_kwDOI9tkbc5J78h8
Error: Cannot read properties of null (reading 'enabledAt')
```

**Comment by peter-evans** [comment]
I tested the action with merge queues and it appears to work fine.

See https://github.com/create-pull-request/auto-merge-queue/pull/2
