### ISSUE TITLE
Failed to enable automerge - Auto-merge on, PAT with Repo access, protected branch with requirements

### ISSUE THREAD

**Issue by 06kellyjac** [peter-evans/enable-pull-request-automerge#79]
I'm getting `Error: Failed to enable auto-merge`

https://github.com/06kellyjac/suckless-git-overlay/runs/2355710781?check_suite_focus=true

I've got auto merge enabled

![image](https://user-images.githubusercontent.com/9866621/114921035-04b54f80-9e22-11eb-9b84-485c84ddbcd0.png)

The branch is protected and requires the tests to pass

![image](https://user-images.githubusercontent.com/9866621/114921149-231b4b00-9e22-11eb-900b-43c7e76e2a23.png)

The auto-merge button shows up if I look after it's been created

![automerge](https://user-images.githubusercontent.com/9866621/114921283-4e059f00-9e22-11eb-8db5-3cc889c689e8.png)

But for some reason the action can't enable it

Is there anything else I can do to debug this? Or do you have any idea what could be the cause?
Maybe it's because it's triggering push and pr tests??

**Comment by peter-evans** [comment]
Hi @06kellyjac 

Interesting. I can't immediately see anything wrong.

You are using `merge-method: squash` but your screenshot shows `Enable auto-merge (rebase)`. Could you check that squash merges are enabled for your repository.

![image](https://user-images.githubusercontent.com/18365890/114959434-0887b700-9ea0-11eb-86c9-9801bc97854b.png)

**Comment by 06kellyjac** [comment]
oooh, i totally thought that param was changed to rebase. that might be the ticket

**Comment by 06kellyjac** [comment]
Yep that resolved the issue
