### ISSUE TITLE
Action fails after new release v2.4.0

### ISSUE THREAD

**Issue by VaidyaAkhil-Groww** [peter-evans/enable-pull-request-automerge#910]
After the `v2.4.0` is released our workflows started breaking, have attached relevant screenshots, please check.

`Download action repository 'peter-evans/enable-pull-request-automerge@v2' (SHA:51b7924f8e9b3bb022e2bb6f30e478e199bfca43)`

`.../_temp/13c7f0de-517d-4ec7-9fc3-993eb6814875.sh: line 1: merge-method=${INPUT,,}: bad substitution
Error: Process completed with exit code 1.`

<img width="1146" alt="Screenshot 2023-03-08 at 12 10 24 PM" src="https://user-images.githubusercontent.com/113657479/223638421-d7d6f39e-5f97-4df0-b838-49f5a5c9e709.png">
<img width="726" alt="Screenshot 2023-03-08 at 12 11 30 PM" src="https://user-images.githubusercontent.com/113657479/223638431-e4e18328-972e-40ab-91eb-99aaa71cd148.png">

### Other Relevant Info
- Running on `self-hosted` runners
- The failures encountered till now are all on `mac-mini` machines as of now

**Comment by peter-evans** [comment]
Hi @VaidyaAkhil-Groww 

Apologies, I'll take a look at what is happening here.

In the meantime I've reverted the major tag so that `v2` points to `v2.3.0`.

**Comment by peter-evans** [comment]
What runner are you executing the workflow on? e.g. `runs-on: ubuntu-latest`

**Comment by VaidyaAkhil-Groww** [comment]
We are using `self-hosted` runners, I just checked the 3 failures we encountered are all on mac-mini.

**Comment by peter-evans** [comment]
It looks like there are `bash` differences between runners. I think I'll create a new release to revert back for now.

**Comment by VaidyaAkhil-Groww** [comment]
Thanks

**Comment by peter-evans** [comment]
Hi @VaidyaAkhil-Groww 

I think I've fixed the issue. This time I've released as a new major version, `v3`, in case there are unexpected breaking changes.
